import { Hero } from '../_models';

export const HEROES: Hero[] = [
  { price: 111, name: 'Envy', alias: 'Emiliy Claver', description: 'Female. Originally shattered by her Empath power, this hero has quickly learned to harness her overwhelming ability to feel the emotions of others and hear their thoughts. Through growth and control she can now alter and change how people feel, either gracing someone with feelings such as bliss, happiness, or peace, or she can overload someone with feelings of rage, depression, or terror. ', power: 'Emotional Warrior' },
  { price: 121, name: 'Transference', alias: 'Narco Brown', description: 'Male. A charming and suave individual with the ability to displace and transfer the consciousness or essence of different individuals into bodies that are not their own. He can not only transfer his own state of being into another individual and gain full control of their actions; but he can also transfer another individual’s consciousness into someone else. This lasts as long as he wishes. ', power: 'Teleporting Esper' },
  { price: 131, name: 'Radio', alias: 'Ben Framer', description: 'Male. A young and upcoming hero new to his powers whom possess the ability to alter and change electromagnetic waves. He has aided the U.S. military in numerous overseas Ops by eliminating and controlling enemy communications. With substantial control and willfulness he can also learn to concentrate waves as a means of defense causing the damage to DNA cells and resulting in a rapid onset of cancer in any living being. ', power: 'Electromagnetic Control' },
  { price: 141, name: 'Gia', alias: 'Mother Maria', description: 'Female. Rooted to the earth, this peaceful but confident hero has the ability to create, alter, or destroy all life with a single touch. She focuses on the growth of plant life, in an effort to produce large amounts of natural food sources; as well as replenishes dying forests and near extinct animals. But if she chooses, her powers also have the ability to rapidly increase any lifespan by speeding up and altering their normal timeline rushing any living thing suddenly to death. ', power: 'Power of Life and Death' },
  { price: 151, name: 'Ravage', alias: 'Kate Jasper', description: 'Female. With an enhanced telekinesis ability. This grounded hero can not only move objects with her mind, but with just a quick thought she can accelerate the molecules that make up an object; so rapidly, that they explode. With her ability she can be a great force of good, helping to destroy targets from miles away, or she can demolish nations within seconds leaving havoc in her wake. ', power: 'Telekinesis Power' },
  { price: 161, name: 'Binary', alias: 'Seth Reburin', description: 'Male. This quiet loner can manipulate his cellular DNA which allows him to become any object he touches, making him genetically identical to it. Not only can he become a replica of the object, but with larger objects he can even become a part them. Whether it be a steel door, a cell phone, or a simple droplet of water, this hero can truly become anything. ', power: 'Molecular Shapshifter' },
  { price: 171, name: 'Katana', alias: 'Akari Akaza', description: 'Female. Born of Japanese descent this smart and cunning hero retains the power of the majestic Kitsune (Fox).  While there are 13 different abilities the Kitsune can obtain, this hero currently has the ability to control wind, thunder, and lightning while also having the ability to shapeshift into any other living creature great or small. Foxes are inherently known to be tricksters, so while she mostly uses her powers for the greater good, don’t be surprised if find she has had a little harmless fun at your expense.', power: 'Elemental Swordswoman' },
  { price: 181, name: 'Dragone', alias: 'Ryu Yellowstone', description: 'Male. A fiery hot head with a grudge against conformed society. This new and unlikely hero has the power to convert the rage within into physical flames. Unlike normal fire, the flames he possesses equate to the temperature of molten magma and can destroy any and all things. Not only can he create and control fire, but his body can withstand any damage it may cause to him. On top of this he also has the ability to become the flame; quickly earning him the nickname “the dragon”.', power: 'Fire/Magma Power' },
  { price: 191, name: 'Revel', alias: 'Unknown', description: 'Female. A rogue and untamable character that does not work well with others. This unlikely hero has the ability to enter the mind of an individual by simply touching a picture of them. Once inside she can sift through past memories and current thoughts, as well as creating a false distorted version of their reality that the individual believes is real. Once she is finished the individual returns to daily life, unaware of what they have done or said while in the trance; unaware that what they have experienced was not real. ', power: 'Covert Mindwalker' },
  { price: 201, name: 'Panto', alias: 'Julius Marcuppio', description: 'Male. Highly intelligent with a thirst for knowledge this hero has the ability to obtain and learn any amount of information by simply inhaling it from their source. Known as the “breath of life” this brainiac has learned over 6,000 languages, both dead and spoken. He can instantly retain and access historical facts, war data, blueprints, and other useful intel. His power also works on individuals, allowing him to gain access to any knowledge or information they have learned in the past or present.', power: 'Rapid Comprehension' }
];


